In [1]:
Project = '/Users/daehwa/Library/CloudStorage/OneDrive-Personal/Junlab/Projects/Adipocyte'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

plt.rcParams.update(plt.rcParamsDefault)

mpl.rcParams['font.sans-serif'] = "Arial"
mpl.rcParams['font.family'] = "sans-serif"

plt.rcParams['ps.useafm']=True
plt.rcParams['pdf.fonttype']=42

plt.rc('font', size=7)          # controls default text sizes
plt.rc('axes', titlesize=8)     # fontsize of the axes title
plt.rc('axes', labelsize=8)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=6)    # fontsize of the tick labels
plt.rc('ytick', labelsize=6)    # fontsize of the tick labels
plt.rc('legend', fontsize=6)    # legend fontsize
suptitlesize = 8

plt.rc('axes', axisbelow=True) #push axes to back
plt.rcParams['axes.linewidth'] = 0.5

In [2]:
repre = pd.read_csv(f'{Project}/Results/Tables/conversion_tables/representative-isoforms.txt', sep='\t', usecols=[0,1], header=None, names=['gene_id','transcript_id'])
display(repre)

full_name = pd.read_csv('/Users/daehwa/Library/CloudStorage/OneDrive-Personal/Junlab/Data_Library/GSEA/chip/Mouse_Ensembl_Gene_ID_MSigDB.v2022.1.Mm.chip', sep='\t')
full_name = full_name.rename(columns={'Probe Set ID':'gene_id', 'Gene Symbol':'gene_name', 'Gene Title':'full_name'})
full_name['full_name'] = full_name['full_name'].str.split('[').str[0]

display(full_name)

                     gene_id          transcript_id
0       ENSMUSG00000000001.5   ENSMUST00000000001.5
1      ENSMUSG00000000003.16  ENSMUST00000000003.14
2      ENSMUSG00000000028.16  ENSMUST00000000028.14
3      ENSMUSG00000000031.17   ENSMUST00000136359.8
4      ENSMUSG00000000037.18  ENSMUST00000019101.11
...                      ...                    ...
55354   ENSMUSG00002076988.1   ENSMUST00020182589.1
55355   ENSMUSG00002076989.1   ENSMUST00000083836.4
55356   ENSMUSG00002076990.1   ENSMUST00020183326.1
55357   ENSMUSG00002076991.1   ENSMUST00020182837.1
55358   ENSMUSG00002076992.1   ENSMUST00020181762.1

[55359 rows x 2 columns]

,gene_id,gene_name,full_name
0,ENSMUSG00000000001,Gnai3,guanine nucleotide binding protein (G protein)...
1,ENSMUSG00000000003,Pbsn,probasin
2,ENSMUSG00000000028,Cdc45,cell division cycle 45
3,ENSMUSG00000000031,H19,"H19, imprinted maternally expressed transcript"
4,ENSMUSG00000000037,Scml2,Scm polycomb group protein like 2
...,...,...,...
43242,ENSMUSG00002076818,SNORD14,Small nucleolar RNA SNORD14
43243,ENSMUSG00002076971,Snord100,"small nucleolar RNA, C/D box 100"
43244,ENSMUSG00002076975,Gm23823,"predicted gene, 23823"
43245,ENSMUSG00002076989,Gm23510,"predicted gene, 23510"
43246,ENSMUSG00002076990,Gm22711,"predicted gene, 22711"

In [3]:
RNA_logFC = pd.read_csv(f'{Project}/Results/Tables/CPM_RD_calculation/v20221217/adi_RNA_avg_log2FC.tsv', sep='\t').drop(columns='gene_name')
RNA_logFC['gene_id'] = RNA_logFC['gene_id'].str.split('.').str[0]

# RD_logFC = pd.read_csv(f'{Project}/Results/Tables/CPM_RD_calculation/v20221217/adi_RD_avg_log2FC.tsv', sep='\t').drop(columns='gene_name')
# RD_logFC['gene_id'] = RD_logFC['gene_id'].str.split('.').str[0]

PT_logFC = pd.read_csv(f'{Project}/Results/Tables/Proteome/PT_Norm_FC_calculation/v20230104/adi_PT_avg_log2FC.tsv', sep='\t')
PT_conv = pd.read_csv(f'{Project}/Results/Tables/Proteome/adi_proteome_logExp_geneid.tsv', sep='\t', usecols=('uniprot_id','gene_id')).drop_duplicates(subset='gene_id')
PT_logFC = pd.merge(PT_conv, PT_logFC, on='uniprot_id').drop(columns='uniprot_id')

FC = pd.merge(RNA_logFC, PT_logFC, on='gene_id', how='outer')
display(FC)

                  gene_id        R4        R8       PT4       PT8
0      ENSMUSG00000033845  1.919982  2.397623  0.974294  0.987729
1      ENSMUSG00000025903  0.564052  0.894128  0.255831  0.685794
2      ENSMUSG00000033813 -0.823592  0.210519 -0.406827 -0.486495
3      ENSMUSG00000033793  0.192070 -0.043765  0.561826  0.770738
4      ENSMUSG00000025907 -0.130110  0.328257 -0.272296 -0.053266
...                   ...       ...       ...       ...       ...
12294  ENSMUSG00000072625       NaN       NaN  0.130366  0.081770
12295  ENSMUSG00000073435       NaN       NaN  0.798697  1.295661
12296  ENSMUSG00000051149       NaN       NaN  0.028960 -0.282776
12297  ENSMUSG00000024391       NaN       NaN -0.307144  0.157581
12298  ENSMUSG00000039131       NaN       NaN  0.184318  0.086028

[12299 rows x 5 columns]

In [4]:
stalling_change_all = pd.read_csv(f'{Project}/Results/Tables/Ribosome_stalling/v20230730/adi_stalling-change_FEresult.tsv', sep='\t')
display(stalling_change_all)

stalling_estimated_genes = stalling_change_all[['transcript_id']].drop_duplicates()
stalling_estimated_genes = pd.merge(repre, stalling_estimated_genes, on='transcript_id')
stalling_estimated_genes['gene_id'] = stalling_estimated_genes['gene_id'].str.split('.').str[0]
display(stalling_estimated_genes)

,transcript_id,reltostart-asite,D4_OR,D4_p,D4_FDR,D8_OR,D8_p,D8_FDR
0,ENSMUST00000000001.5,33,0.308259,0.356685,1.0,0.774119,1.000000,1.0
1,ENSMUST00000000001.5,36,0.926156,1.000000,1.0,1.161905,1.000000,1.0
2,ENSMUST00000000001.5,39,0.000000,0.231122,1.0,1.744579,0.667567,1.0
3,ENSMUST00000000001.5,42,inf,0.500555,1.0,NaN,1.000000,1.0
4,ENSMUST00000000001.5,45,0.462733,0.611056,1.0,0.580519,1.000000,1.0
...,...,...,...,...,...,...,...,...
2238001,ENSMUST00000239525.1,10461,0.000000,1.000000,1.0,0.000000,1.000000,1.0
2238002,ENSMUST00000239525.1,10464,1.561936,1.000000,1.0,0.000000,1.000000,1.0
2238003,ENSMUST00000239525.1,10467,0.520467,0.494876,1.0,0.000000,0.598884,1.0
2238004,ENSMUST00000239525.1,10470,0.669209,0.749590,1.0,0.767953,1.000000,1.0
2238005,ENSMUST00000239525.1,10473,0.173410,0.100334,1.0,1.194996,0.686639,1.0

                 gene_id          transcript_id
0     ENSMUSG00000000001   ENSMUST00000000001.5
1     ENSMUSG00000000056   ENSMUST00000103015.4
2     ENSMUSG00000000078   ENSMUST00000000080.8
3     ENSMUSG00000000088   ENSMUST00000000090.8
4     ENSMUSG00000000127  ENSMUST00000000129.14
...                  ...                    ...
5019  ENSMUSG00000118491   ENSMUST00000142247.8
5020  ENSMUSG00000118552   ENSMUST00000238938.2
5021  ENSMUSG00000118653   ENSMUST00000239472.2
5022  ENSMUSG00000118664   ENSMUST00000239509.1
5023  ENSMUSG00000118667   ENSMUST00000239525.1

[5024 rows x 2 columns]

In [5]:
stalling_change = pd.read_csv(f'{Project}/Results/Tables/Ribosome_stalling/v20230730/adi_stalling-change_FEresult_sig.tsv', sep='\t')
stalling_change = pd.merge(repre, stalling_change, on='transcript_id', how='right').sort_values('D8_FDR')
# stalling_change = stalling_change[stalling_change['aa-asite']=='E']
stalling_change = stalling_change[stalling_change['D8_FDR']<0.01]
stalling_change = stalling_change[stalling_change['D8_OR']>1]
# stalling_change['D8_log2OR'] = np.log2(stalling_change['D8_OR'])
stalling_change['gene_id'] = stalling_change['gene_id'].str.split('.').str[0]

display(stalling_change)

,gene_id,transcript_id,asite,reltostart-asite,codon-asite,aa-asite,D4_OR,D4_p,D4_FDR,D8_OR,D8_p,D8_FDR
23191,ENSMUSG00000026043,ENSMUST00000087883.13,3312,3102,GAA,E,1.803037,9.700806e-139,4.669321e-136,2.950872,0.000000,0.000000
1275,ENSMUSG00000001506,ENSMUST00000001547.8,1684,1539,GAA,E,1.458798,2.121448e-122,3.040035e-120,2.563152,0.000000,0.000000
1985,ENSMUSG00000001506,ENSMUST00000001547.8,4396,4251,UAC,Y,2.043079,4.208669e-79,3.547660e-77,5.968501,0.000000,0.000000
22993,ENSMUSG00000026043,ENSMUST00000087883.13,2547,2337,GAA,E,1.955971,1.695743e-96,3.060816e-94,4.260758,0.000000,0.000000
917,ENSMUSG00000001506,ENSMUST00000001547.8,226,81,GAA,E,3.045111,1.525542e-234,5.465254e-232,10.141205,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2208,ENSMUSG00000002957,ENSMUST00000003038.12,1159,972,UUG,L,2.130350,1.072801e-03,4.924158e-01,2.600783,0.000022,0.009951
13798,ENSMUSG00000031812,ENSMUST00000034270.17,368,204,CGG,R,2.531474,3.353894e-05,3.521589e-03,2.332870,0.000190,0.009973
22000,ENSMUSG00000055447,ENSMUST00000084838.14,1060,918,UAU,Y,3.201099,1.253081e-02,9.441867e-01,4.961735,0.000099,0.009985
24671,ENSMUSG00000022665,ENSMUST00000099498.10,2418,1752,AAA,K,1.258972,4.041560e-01,1.000000e+00,2.641265,0.000161,0.009993
24680,ENSMUSG00000022665,ENSMUST00000099498.10,3150,2484,GAA,E,1.501061,1.272029e-01,9.160579e-01,2.789365,0.000156,0.009993

In [6]:
codon_data = pd.read_csv(f'{Project}/Results/Tables/Codon_analysis/codon_usage/v20220503/gene-level_codon_usage.tsv', sep='\t')
codon_data = codon_data.rename(columns={'Transcript_ID':'transcript_id', 'Gene_ID':'gene_id', 'Gene_name':'gene_name'})
codon_data['Total_codon_num'] = codon_data.iloc[:,5:].sum(axis=1)
codon_data = pd.merge(repre, codon_data, on=['transcript_id','gene_id'])

for codon in codon_data.iloc[:,5:-1]:
    codon_data[codon] = codon_data[codon] / codon_data['Total_codon_num'] * 100

# display(codon_data)

codontab = {
    'TCA': 'S', 'TCC': 'S', 'TCG': 'S', 'TCT': 'S',
    'TTC': 'F', 'TTT': 'F',
    'TTA': 'L', 'TTG': 'L', 'CTA': 'L', 'CTC': 'L', 'CTG': 'L','CTT': 'L',
    'TAC': 'Y', 'TAT': 'Y',
    # 'TAA': '*', 'TAG': '*', 'TGA': '*',
    'TGC': 'C', 'TGT': 'C',
    'TGG': 'W',
    'CCA': 'P', 'CCC': 'P', 'CCG': 'P', 'CCT': 'P',
    'CAC': 'H', 'CAT': 'H',
    'CAA': 'Q', 'CAG': 'Q',
    'CGA': 'R', 'CGC': 'R', 'CGG': 'R','CGT': 'R', 'AGA': 'R', 'AGG': 'R',
    'ATA': 'I', 'ATC': 'I', 'ATT': 'I',
    'ATG': 'M',
    'ACA': 'T', 'ACC': 'T', 'ACG': 'T', 'ACT': 'T',
    'AAC': 'N', 'AAT': 'N',
    'AAA': 'K', 'AAG': 'K',
    'AGC': 'S', 'AGT': 'S',
    'GTA': 'V', 'GTC': 'V', 'GTG': 'V', 'GTT': 'V',
    'GCA': 'A', 'GCC': 'A', 'GCG': 'A', 'GCT': 'A',
    'GAC': 'D', 'GAT': 'D',
    'GAA': 'E', 'GAG': 'E',
    'GGA': 'G', 'GGC': 'G', 'GGG': 'G', 'GGT': 'G'
}

AAs = []
codons = []
for codon, AA in codontab.items():
    AAs.append(AA)
    codons.append(codon.replace('T','U'))

AA_codon = pd.DataFrame({'AA':AAs, 'codon':codons})
AA2codon = AA_codon.groupby('AA')['codon'].apply(list).to_dict()
# display(AA2codon)

AA_ratio_data = codon_data[['transcript_id','gene_id','gene_name','Total_codon_num']].copy()
for AA in AA2codon:
    AA_ratio_data[AA] = codon_data[AA2codon[AA]].sum(axis=1)

AA_ratio_data['gene_id'] = AA_ratio_data['gene_id'].str.split('.').str[0]
display(AA_ratio_data)

AA_ratio_data_BG = pd.merge(stalling_estimated_genes[['gene_id']], AA_ratio_data, on='gene_id')
display(AA_ratio_data_BG)

,transcript_id,gene_id,gene_name,Total_codon_num,A,C,D,E,F,G,...,M,N,P,Q,R,S,T,V,W,Y
0,ENSMUST00000000001.5,ENSMUSG00000000001,Gnai3,355,6.760563,2.816901,7.042254,8.450704,4.788732,5.352113,...,2.253521,3.943662,0.845070,3.661972,5.633803,6.197183,6.478873,6.197183,0.845070,4.225352
1,ENSMUST00000000003.14,ENSMUSG00000000003,Pbsn,175,3.428571,2.285714,2.285714,7.428571,4.000000,5.714286,...,5.142857,5.714286,2.285714,4.000000,5.714286,4.000000,4.571429,7.428571,0.571429,5.142857
2,ENSMUST00000000028.14,ENSMUSG00000000028,Cdc45,567,5.467372,1.940035,7.760141,7.231041,5.467372,3.527337,...,2.821869,3.350970,2.469136,4.938272,5.291005,8.465608,5.114638,7.054674,1.410935,3.350970
3,ENSMUST00000019101.11,ENSMUSG00000000037,Scml2,906,7.395143,1.545254,6.512141,5.849890,4.304636,8.057395,...,0.883002,2.649007,8.830022,4.194260,6.622517,7.174393,8.498896,5.077263,1.766004,0.662252
4,ENSMUST00000000049.6,ENSMUSG00000000049,Apoh,346,5.491329,6.647399,3.468208,5.780347,5.491329,6.358382,...,2.023121,3.757225,9.826590,1.734104,4.046243,5.780347,6.936416,6.069364,1.445087,4.046243
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21929,ENSMUST00000239545.1,ENSMUSG00000118670,Muc19,7525,19.933555,1.794020,1.235880,2.923588,0.611296,9.581395,...,0.225914,2.019934,5.940199,1.116279,2.232558,22.019934,22.325581,2.790698,0.199336,0.823920
21930,ENSMUST00000239552.1,ENSMUSG00000118671,Eppk1,3459,7.950275,0.896213,5.174906,7.776814,2.428448,8.123735,...,1.850246,1.618965,4.394334,6.620411,6.909511,6.042209,6.909511,7.805724,0.780572,2.515178
21931,ENSMUST00000239554.1,ENSMUSG00000118672,Muc4,3991,4.535204,1.202706,2.630920,3.081934,1.929341,4.585317,...,2.129792,3.583062,6.740165,6.940616,3.257329,18.892508,20.370834,3.958908,0.676522,1.353044
21932,ENSMUST00010126032.3,ENSMUSG00001074846,Iqcf3,204,8.823529,1.960784,5.392157,16.176471,0.490196,2.450980,...,0.980392,4.411765,3.431373,8.823529,6.372549,4.901961,5.392157,3.921569,2.450980,0.490196
21933,ENSMUST00000105569.5,ENSMUSG00002076083,Klhl17,641,9.984399,2.184087,4.992200,4.992200,2.184087,7.332293,...,2.340094,2.964119,6.084243,2.964119,7.800312,9.516381,5.148206,8.892356,1.248050,3.120125

,gene_id,transcript_id,gene_name,Total_codon_num,A,C,D,E,F,G,...,M,N,P,Q,R,S,T,V,W,Y
0,ENSMUSG00000000001,ENSMUST00000000001.5,Gnai3,355,6.760563,2.816901,7.042254,8.450704,4.788732,5.352113,...,2.253521,3.943662,0.845070,3.661972,5.633803,6.197183,6.478873,6.197183,0.845070,4.225352
1,ENSMUSG00000000056,ENSMUST00000103015.4,Narf,463,6.911447,3.455724,5.615551,8.207343,3.887689,6.047516,...,1.295896,2.375810,3.887689,5.615551,5.183585,7.775378,4.751620,7.775378,0.647948,2.807775
2,ENSMUSG00000000078,ENSMUST00000000080.8,Klf6,319,3.134796,4.075235,5.642633,8.150470,4.075235,5.956113,...,0.940439,2.821317,7.210031,2.821317,6.269592,15.673981,5.015674,3.761755,1.567398,2.194357
3,ENSMUSG00000000088,ENSMUST00000000090.8,Cox5a,147,14.285714,2.721088,6.122449,7.482993,2.040816,4.761905,...,0.680272,2.721088,6.802721,0.680272,7.482993,4.761905,4.081633,6.122449,1.360544,3.401361
4,ENSMUSG00000000127,ENSMUST00000000129.14,Fer,824,4.854369,1.456311,4.611650,9.466019,2.791262,4.733010,...,2.912621,4.126214,3.155340,6.796117,3.762136,6.432039,4.975728,6.432039,1.092233,3.276699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5012,ENSMUSG00000118491,ENSMUST00000142247.8,Gm44505,530,9.056604,2.830189,4.905660,11.320755,1.320755,5.471698,...,0.943396,1.698113,8.301887,3.962264,8.867925,8.113208,4.716981,3.396226,0.377358,2.075472
5013,ENSMUSG00000118552,ENSMUST00000238938.2,Rplp2-ps1,116,17.241379,0.000000,8.620690,8.620690,1.724138,11.206897,...,0.862069,3.448276,4.310345,0.862069,1.724138,10.344828,0.000000,6.896552,0.000000,1.724138
5014,ENSMUSG00000118653,ENSMUST00000239472.2,RP23-180C14.7,224,9.821429,1.339286,4.464286,8.035714,2.232143,8.482143,...,1.339286,4.464286,7.589286,0.892857,5.357143,4.910714,5.357143,4.464286,0.446429,2.232143
5015,ENSMUSG00000118664,ENSMUST00000239509.1,Tusc3,349,7.736390,1.719198,3.151862,3.438395,6.590258,6.876791,...,3.438395,4.871060,4.297994,4.871060,7.736390,7.449857,3.151862,5.730659,1.432665,3.724928
5016,ENSMUSG00000118667,ENSMUST00000239525.1,Ahnak2,3502,10.508281,0.285551,6.310680,7.909766,2.341519,8.452313,...,2.141633,0.513992,10.137065,4.940034,2.684180,8.766419,3.226728,8.909195,0.371216,0.428327

In [7]:
AA_ratio_data_BG_FC = pd.merge(AA_ratio_data_BG, FC, on='gene_id', how='left')
display(AA_ratio_data_BG_FC)

,gene_id,transcript_id,gene_name,Total_codon_num,A,C,D,E,F,G,...,R,S,T,V,W,Y,R4,R8,PT4,PT8
0,ENSMUSG00000000001,ENSMUST00000000001.5,Gnai3,355,6.760563,2.816901,7.042254,8.450704,4.788732,5.352113,...,5.633803,6.197183,6.478873,6.197183,0.845070,4.225352,-0.982948,-1.023048,-0.390694,-0.634272
1,ENSMUSG00000000056,ENSMUST00000103015.4,Narf,463,6.911447,3.455724,5.615551,8.207343,3.887689,6.047516,...,5.183585,7.775378,4.751620,7.775378,0.647948,2.807775,1.186888,1.282568,0.248422,0.727179
2,ENSMUSG00000000078,ENSMUST00000000080.8,Klf6,319,3.134796,4.075235,5.642633,8.150470,4.075235,5.956113,...,6.269592,15.673981,5.015674,3.761755,1.567398,2.194357,-1.115713,-1.088835,NaN,NaN
3,ENSMUSG00000000088,ENSMUST00000000090.8,Cox5a,147,14.285714,2.721088,6.122449,7.482993,2.040816,4.761905,...,7.482993,4.761905,4.081633,6.122449,1.360544,3.401361,2.407410,2.986577,1.045512,1.645258
4,ENSMUSG00000000127,ENSMUST00000000129.14,Fer,824,4.854369,1.456311,4.611650,9.466019,2.791262,4.733010,...,3.762136,6.432039,4.975728,6.432039,1.092233,3.276699,-1.326498,-0.244820,-0.417156,-0.009094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5012,ENSMUSG00000118491,ENSMUST00000142247.8,Gm44505,530,9.056604,2.830189,4.905660,11.320755,1.320755,5.471698,...,8.867925,8.113208,4.716981,3.396226,0.377358,2.075472,NaN,NaN,NaN,NaN
5013,ENSMUSG00000118552,ENSMUST00000238938.2,Rplp2-ps1,116,17.241379,0.000000,8.620690,8.620690,1.724138,11.206897,...,1.724138,10.344828,0.000000,6.896552,0.000000,1.724138,NaN,NaN,NaN,NaN
5014,ENSMUSG00000118653,ENSMUST00000239472.2,RP23-180C14.7,224,9.821429,1.339286,4.464286,8.035714,2.232143,8.482143,...,5.357143,4.910714,5.357143,4.464286,0.446429,2.232143,NaN,NaN,NaN,NaN
5015,ENSMUSG00000118664,ENSMUST00000239509.1,Tusc3,349,7.736390,1.719198,3.151862,3.438395,6.590258,6.876791,...,7.736390,7.449857,3.151862,5.730659,1.432665,3.724928,-0.141956,-0.760043,0.500249,0.595786
5016,ENSMUSG00000118667,ENSMUST00000239525.1,Ahnak2,3502,10.508281,0.285551,6.310680,7.909766,2.341519,8.452313,...,2.684180,8.766419,3.226728,8.909195,0.371216,0.428327,-1.368068,-2.526532,NaN,NaN

In [8]:
stall_num_AA_rank = list(stalling_change.groupby('aa-asite').size().reset_index(name='stall_num')[1:].sort_values('stall_num', ascending=False)['aa-asite'])

----

In [9]:
N=10

tmp = AA_ratio_data_BG_FC.sort_values('E')

Nth = len(tmp)//N
E_content_Nth = {}
for i in range(N):
    E_content_Nth[i+1] = tmp[ Nth*i : Nth*(i+1)]
    if i==(N-1) : E_content_Nth[i+1] = tmp[ Nth*i : ]

# display(E_content_Nth[N])

E_stalled_genes = stalling_change[stalling_change['aa-asite']=='E'][['gene_id']].drop_duplicates()
# display(E_stalled_genes)

In [10]:
Glu_rich_E_stalled = pd.merge(E_content_Nth[N][['gene_id']], E_stalled_genes, on='gene_id')
display(Glu_rich_E_stalled)

Glu_rich_E_stalled.to_csv('Glu-rich-stalled_genes.txt', header=False, index=False)

Glu_rich_E_stalled_table = pd.merge(Glu_rich_E_stalled, full_name, on='gene_id', how='left')
Glu_rich_E_stalled_table = pd.merge(Glu_rich_E_stalled_table, AA_ratio_data_BG_FC[['gene_id','E']], on='gene_id')
Glu_rich_E_stalled_table = pd.merge(Glu_rich_E_stalled_table, FC, on='gene_id', how='left').sort_values('E', ascending=False)
display(Glu_rich_E_stalled_table)
Glu_rich_E_stalled_table.to_csv('Glu-rich-stalled_genes_table.tsv', sep='\t', index=False)

                gene_id
0    ENSMUSG00000020463
1    ENSMUSG00000053774
2    ENSMUSG00000071533
3    ENSMUSG00000063273
4    ENSMUSG00000004451
..                  ...
201  ENSMUSG00000031799
202  ENSMUSG00000028464
203  ENSMUSG00000027940
204  ENSMUSG00000032249
205  ENSMUSG00000030122

[206 rows x 1 columns]

,gene_id,gene_name,full_name,E,R4,R8,PT4,PT8
205,ENSMUSG00000030122,Ptms,parathymosin,34.313725,0.802806,1.158767,-0.083898,0.093654
204,ENSMUSG00000032249,Anp32a,acidic (leucine-rich) nuclear phosphoprotein 3...,23.387097,0.049584,0.601612,-0.134542,0.460264
203,ENSMUSG00000027940,Tpm3,"tropomyosin 3, gamma",20.883534,-1.300733,-1.843680,NaN,NaN
202,ENSMUSG00000028464,Tpm2,"tropomyosin 2, beta",20.701754,-2.965319,-2.222747,-2.602298,-2.222502
201,ENSMUSG00000031799,Tpm4,tropomyosin 4,20.481928,-2.332503,-1.529215,-1.159129,-1.420171
...,...,...,...,...,...,...,...,...
4,ENSMUSG00000004451,Ralb,v-ral simian leukemia viral oncogene B,10.628019,-0.313462,-0.511593,-0.206038,-0.038833
3,ENSMUSG00000063273,Naa15,"N(alpha)-acetyltransferase 15, NatA auxiliary ...",10.623557,0.501781,0.560599,NaN,NaN
2,ENSMUSG00000071533,Pcnp,PEST proteolytic signal containing nuclear pro...,10.614525,-0.327252,-0.136821,-0.003015,-0.202229
1,ENSMUSG00000053774,Ubxn7,UBX domain protein 7,10.612245,-0.091076,0.094331,-0.195001,-0.014858
0,ENSMUSG00000020463,Ppp4r3b,protein phosphatase 4 regulatory subunit 3B,10.596833,0.231509,0.678281,NaN,NaN

In [11]:
AA_ratio_data_BG_FC[['gene_id']].to_csv('BG_genes.txt', header=False, index=False)